app: fiasco-online
service: fiasco-online-playset
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get