app: fiasco-online
service: fiasco-online-playset
plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2

functions:
  GET:
    handler: src/routes/GET.route
    events:
      - http:
          path: /
          method: get
          cors: true
  POST:
    handler: src/routes/POST.route
    events:
      - http:
          path: /
          method: post
          cors: true
  .id-GET:
    handler: src/routes/{id}/GET.route
    events:
      - http:
          path: /{id}
          method: get
          cors: true